---
- hosts: all
  vars:
       ansible_host_key_checking:  false
       become: true
  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install JAVA related Ubuntu packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - openjdk-8-jdk
          - tomcat9
          - tomcat9-examples
          - tomcat9-docs

    - name: Make sure a service is running
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: tomcat9

    - name: Open Tomcat port
      ufw:
        state: enabled
        rule: allow
        port: "8080"
        proto: tcp
        
    # - name: copy war
    #   copy:
    #     src: /var/lib/jenkins/workspace/< your project name >/webapp/target/webapp.war
    #     dest: /opt/docker/< your name >
    # - name: Stop current container
    #   command: docker stop < your name >-devops-container
    #   ignore_errors: yes
    # - name: remove stopped container
    #   command: docker rm < your name>-devops-container
    #   ignore_errors: yes
    # - name: remover docker images # Clean up task
    #   command: docker rmi < your name >-devops-image:latest
    #   ignore_errors: yes # May not find image if first run
    # - name: create docker image using war file
    #   command: docker build -t < your namie >-devops-image:latest .
    #   args:
    #     chdir: /opt/docker/< your name >
    # - name: run container
    #   command: docker run -d --name < your name >-devops-container -p 8081:8080 < your name >-devops-image:latest
